<a href="https://colab.research.google.com/github/Nikhil07-source/Nikhil07-source/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# __NumPy Introduction__

##1. __Fundamentals of NumPy__

NumPy (Numerical Python) is a free and open-source library that is mostly used for mathematical operations in scientific and engineering applications.

- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

**Note:** The array object in NumPy is called ndarray.

### __1.1  Advantages of NumPy__
- It provides an array object that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.
- NumPy arrays are stored in one continuous place in memory, unlike lists.

## __2. NumPy: Array Object__
A NumPy ndarray object can be created by using the array() function.

In [ ]:
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50])
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


### __2.1 Creating NumPy Arrays__
- Create multiple dimensional arrays, such as 0D, 1D, 2D and 3D

In [ ]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0)
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)
# Create a 2D Array
arr2 = np.array([[1,1,1],[1,2,1]])
print ('2D array is', arr2)
# Create a 3D Array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print ('3D array is', arr3)

0D array is 24
1D array is [1 2 3 4]
2D array is [[1 1 1]
 [1 2 1]]
3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


# __Attributes and Functions in Python__

## __1. Attributes of NumPy Arrays__ ##

Few common attributes of NumPy array:
- ndarray.ndim (To get the dimesion of array)
- ndarray.shape (To get the shape of array)
- ndarray.size (To het the size of array)
- ndarray.type (To get the type of array)
- ndarray.itemsize (To get the size of items in array)
- ndarray.data (To get data about array)

In [ ]:
import numpy as np

age = np.array([20,22,24]) #Creating 1d array
print('Following array is:', age)

#Attributes of Array
print('The datatype of above figure is:', type(age)) #Datatype of the array
print('The dimension of above array is:', age.ndim)  #Dimension of the array
print('The shape of above array is:', age.shape)     #Shape of the array
print('The size of above array is:', age.size)       #Size of the array
print('The length of above array is:', age.itemsize) #Length of the array
print('The size of above array is:', age.data)       #Size of the array

Following array is: [20 22 24]
The datatype of above figure is: <class 'numpy.ndarray'>
The dimension of above array is: 1
The shape of above array is: (3,)
The size of above array is: 3
The length of above array is: 8
The size of above array is: <memory at 0x7caba9714b80>


In [ ]:
arr2  =np.array([[12,21,54],[45,45,98]]) #Creating 2d Array
print('Following array is:', arr2)

#Attributes of Array
print('The datatype of above array is:', type(arr2))  #Datatype of the array
print('The dimension of above array is:', arr2.ndim)  #Dimension of the array
print('The shape of above array is:', arr2.shape)     #Shape of the array
print('The size of above array is:', arr2.size)       #Size of the array
print('The length of above array is:', arr2.itemsize) #Length of the array
print('The size of above array is:', arr2.data)       #Size of the array

Following array is: [[12 21 54]
 [45 45 98]]
The datatype of above array is: <class 'numpy.ndarray'>
The dimension of above array is: 2
The shape of above array is: (2, 3)
The size of above array is: 6
The length of above array is: 8
The size of above array is: <memory at 0x7caba9874110>


In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #Creating 3d Array
print('The following array is:', arr3)

#Attributes of Array
print('The datataype of above array is:', type(arr3))  #Datatype of the array
print('The dimension of above array is:', arr3.ndim)   #Dimension of the array
print('The shape of above array is:', arr3.shape)      #Shape of the array
print('The size of above array is:', arr3.size)        #Size of the array
print('The length of above array is:', arr3.itemsize)  #Length of the array
print('The size of above array is:', arr3.data)        #Size of the array

The following array is: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
The datataype of above array is: <class 'numpy.ndarray'>
The dimension of above array is: 3
The shape of above array is: (2, 2, 3)
The size of above array is: 12
The length of above array is: 8
The size of above array is: <memory at 0x7caba9c32d40>


In [ ]:
#Creating 4d array
arr4 = np.array([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]], [[[19, 20, 21], [22, 23, 24]], [[25, 26, 27], [28, 29, 30]], [[31, 32, 33], [34, 35, 36]]]])

#Attributes of Array
print('The datataype of above array is:', type(arr4))  #Datatype of the array
print('The dimension of above array is:', arr4.ndim)   #Dimension of the array
print('The shape of above array is:', arr4.shape)      #Shape of the array
print('The size of above array is:', arr4.size)        #Size of the array
print('The length of above array is:', arr4.itemsize)  #Length of the array
print('The size of above array is:', arr4.data)        #Size of the array

The datataype of above array is: <class 'numpy.ndarray'>
The dimension of above array is: 4
The shape of above array is: (2, 3, 2, 3)
The size of above array is: 36
The length of above array is: 8
The size of above array is: <memory at 0x7caba9c22540>


## __2. NumPy Array Functions__ ##


- `ndarray.reshape`: It is used to reshape (new shape) the current elements of an array.

##__NUMPY ARRAY FUNCTIONS__

###1. Reshape - It is used to reshape (new shape) the current elements of an array. To use this function we have to use "variable_name.reshape()". Inside "()" we can put value which we want to reshape.

###2. Flatten - It returns a copy of the array flattened into a 1D array. To use this function we have to use ".flatten()".

###3. Transpose - It swaps the rows and columns of a 2D array.To use this function we have to use ".transpose()".

In [ ]:
arr3 = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(arr3)
print('The shape of above array is:', arr3.shape)  #Shape of the array

#Now the size of above array is going to change by using reshape function.
new_arr3 = arr3.reshape(3,2,2)    #Shape of the array has been changed to (2,2,3) to (3,2,2)
print(new_arr3)
print('Now the shape of above array is:', new_arr3.shape)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
The shape of above array is: (2, 2, 3)
[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]
Now the shape of above array is: (3, 2, 2)


In [ ]:
arr3d = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(arr3d)

#Now this 3d array is being converted into 1D array using flatten function
arr3d.flatten()

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [ ]:
# Let's create a 2D array for the transpose example
arr2D = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the 2D array
transposed_array = arr2D.transpose()
transposed_array

array([[1, 4],
       [2, 5],
       [3, 6]])

##NUMPY ARITHMETIC STATISTICAL AND STRING FUNCTIONS
###1. Airthmetic Operations - Addition, Substraction, Multiplication, Divison, PowerOf
###2. Statistical Operations - Mean, Median, Standard Deviation, Variance & Percentile

In [ ]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

add = np.add(arr1,arr2)     #Adding of two array using add function.
add

array([50, 70, 90])

In [ ]:
num1 = np.array([50,40,30])
num2 = np.array([10,10,10])

subs = np.subtract(num1,num2)   #Subtraction of two array using substract function.
subs

array([40, 30, 20])

In [ ]:
no1 = np.array([20,40,60])
no2 = np.array([2,4,6])

mul = np.multiply(no1,no2)  #Multiplication of two array using multiply function.
mul

array([ 40, 160, 360])

In [ ]:
number1 = np.array([20,40,60])
number2 = np.array([2,4,6])

div = np.divide(number1,number2) #Divison of two array using divison function.
div

array([10., 10., 10.])

In [ ]:
a = np.array([2,3,4])
b = np.array([20,30,40])

c = np.power(b,a)
c

array([    400,   27000, 2560000])

##STATISTICAL FUNCTIONS USING NUMPY
###1. Mean = Average (sum of all outcomes/number of outcomes)
###2. Median = If data is in odd then sort all data in ascending order and then middle value. If even then select two numbers from middle add them and then divide by 2
###3. Variance =
###4. Standard Deviation =
###5. Percentile = The `np.percentile()` function is used to compute the nth percentile of the array elements.

In [ ]:
data = np.array([21,32,54,21,87])
np.mean(data) #Calculating Mean = Average = sum of all data/ no. of data.

43.0

In [ ]:
new_data = np.array([12,45,55,65,25,41,87,78,54,87])
np.median(new_data) #calculating the median by using median() function.

54.5

In [ ]:
np.std(new_data) #Calculating the Standard Deviation by using std() function.

23.92258347252654

In [ ]:
np.var(new_data) #Calculating Variance by using var() function.

572.29

In [ ]:
x = np.array([[4,6],[1,9]])
np.var(x)

8.5

In [ ]:
# Median
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
np.median(array)
print(np.median(array))
# Mean
np.mean(array)
print(np.mean(array))
# Standard Deviation
np.std(array)
print(np.std(array))
# Variance
np.var(array)
print(np.var(array))

4.0
6.333333333333333
6.944222218666553
48.22222222222222


##3. STRING FUNCTIONS IN NUMPY
###1. Add = Adding two strings by using char.add() function.
###2 Replace = Replacing new string from existing string using char.replace() function.
###3. Upper = Converts string into uppercase by using char.upper() function.
###4. Lower = Converts string in lower case by using char.lower() function.

In [ ]:
import numpy as np

name = np.array(["Neeraj - ","Mukesh - ","Gaurav - "])
address = np.array(["Old ITI","Pithoragarh","Gorapadao"])
#Adding two strings using add() function. It's important to use char.
result = np.char.add(name,address)
print(result)

['Neeraj - Old ITI' 'Mukesh - Pithoragarh' 'Gaurav - Gorapadao']


In [ ]:
x = np.array(['Hello','World'])
#Replacing old string from new String
new = np.char.replace(x,'World','India')
print(new)

['Hello' 'India']


In [ ]:
data = np.array(['my name is nikhil sanwal'])
#Making string in Uppercase by using upper() function.
upper_data = np.char.upper(data)
print(upper_data)

['MY NAME IS NIKHIL SANWAL']


In [ ]:
#Making string in Lowercase by using lower() function.
lower_data = np.char.lower(upper_data)
print(lower_data)

['my name is nikhil sanwal']


##4. INDEXING IN NUMPY -------->
###Indexing is used in many programming languages to find the exact position of any element. Indexing always starts from 0 and goes till end.
##NEGATIVE INDEXING -------->
###Negative Indexing is a term which is used to get the exact position of any element from last. Suppose we don't know the length of indexing, there we can use negative indexing.Negative Indexing always starts from 1.

In [ ]:
d1 = np.array([10,20,30])
d2 = np.array([[40,50,60],[70,80,90]])
d3 = np.array([[[100,110,120],[130,140,150]],[[160,170,180],[190,200,210]]])
#Axcessing "20" digit using indexing in 1st dimensional array
print(d1[1])
#Axcessing "90" digit using indexing in 2nd dimensional array
print(d2[1][2])
#Axcessing "170" digit using indexing in 3rd dimensional array
print(d3[1][0][1])

20
90
170


In [ ]:
d4 = np.array([10,20,30])
d5 = np.array([[40,50,60],[70,80,90]])
d6 = np.array([[[100,110,120],[130,140,150]],[[160,170,180],[190,200,210]]])
#Axcessing "20" digit using negative indexing in 1st dimensional array
print(d4[-2])
#Axcessing "90" digit using negative indexing in 2nd dimensional array
print(d5[-1][-1])
#Axcessing "170" digit using negative indexing in 3rd dimensional array
print(d6[-1][-2][-2])

20
90
170


##5. SLICING
###- Slicing means to cut down in pieces. Here we will slice our given data into pices as our required.
###- [start:stop:step] this is basic fundamental we have to know. Now we will use this in our code below.
###- Slicing always start from 0 as indexing does.

In [ ]:
arr1 = np.array([10,20,30,40,50,60,70,80,90,100])
#Now here we are getting element whose indexing is 1 till 8 - 1 = 7th indexing in 1 Dimensional Array.
arr1[1:8] #20,30,40,50,60,70,80
#Now here we are extracting element with 1st indexing till 8 - 1 = 7th indexing on jump of every 2nd indexing.
arr1[1:8:2] #Start:Stop:Step

array([20, 40, 60, 80])

In [ ]:
arr2 = np.array([[10,20,30,40,50,60,70,80,90,100],[110,120,130,140,150,160,170,180,190,200]])
#Now here we are getting element whose indexing is 1 till 8 - 1 = 7th indexing in 2 Dimensional Array.First we are giving indexing.
arr2[0][1:8]
#Here we mean to get 0th index element then Start from 1st element till 8 - 1 = 7th element.
arr2[0, 1:8]  #20,30,40,50,60,70,80
#Now here we are extracting element with 1st indexing till 8 - 1 = 7th indexing on jump of every 2nd indexing.
arr2[0, 1:8:2]

array([20, 40, 60, 80])

In [ ]:
arr3 = np.array([[[1,2,3,4,5,6,7,8,9,10],[10,11,12,13,14,15,16,17,18,19]],[[20,21,22,23,24,25,26,27,28,29],[30,31,32,33,34,35,36,37,38,39]]])
#Same as 2d array, first we define the indexing and then we sliced.
arr3[1,0, 2:9] #22,23,24,25,26,27,28
#Now here we are extracting element with 1st indexing till 8 - 1 = 7th indexing on jump of every 2nd indexing.
arr3[1,0, 2:9:2]

array([22, 24, 26, 28])